### ISSUE TITLE
Wrong display order in movieclips with drawing object

### ISSUE THREAD

**Issue by NemoStein** [openfl/swf#99]
In swflite (tested on HTML5 and Neko) the display order of a drawing object that is created after the first frame is different from the Animate/Flash timeline (the drawing object goes to the top).

To reproduce, create (in Animate/Flash) a Movielip with two layers and two frames.
Create any shape in the top layer and let it spam to the second frame.
In the second layer (the bottom one), create a keyframe on the second frame and draw a drawing object on it.

![image](https://cloud.githubusercontent.com/assets/2738812/20139204/1e6312f8-a66c-11e6-9333-c5efd4151c74.png)

Link this clip and import on a OpenFL project:
```haxe
addChild(Assets.getMovieClip('test:Test'));
```
[Here is a zip](https://github.com/openfl/swf/files/580767/Test.zip) with a test project (.fla file included)

Edit: Just stumbled upon other situation where this happens, but with movieclips (with drawing objects inside) and a TextField. The common factor here is the multiframe creation.

**Comment by jgranick** [comment]
Thank you for the sample :smile:

I believe I have this fixed

https://github.com/openfl/openfl/commit/4201fe0dc214f4b0f4092ffdffdf1bba74f061f5

The issue is when a higher depth is already displayed, the later depth is not properly sorted behind it. This implementation tries to keep a separate depth array sorted, so we can properly insert objects behind or between other objects on a new frame.

I merged the SWF library code into OpenFL proper, recently. I don't like that we don't have a solution for SWFLite on Flash at the moment (perhaps we should use regular SWF embedding there?) but baking into MovieClip and SimpleButton gives some good possibilities (like custom base classes for SWF symbols)

**Comment by NemoStein** [comment]
I just installed OpenFL and Lime from git to try this, but "something wrong is not right" in the TextField class.
```
TextField.hx:1795 Uncaught TypeError: Cannot set property 'format' of undefined(…)
```

**Comment by jgranick** [comment]
Do you have a way I can reproduce this?

The first textFormat range is supposed to always be defined, from what I can tell, so if this is happening, it means some edge case where something is not set properly. Being able to reproduce what's triggering it for you would probably make it fast to fix

**Comment by NemoStein** [comment]
Uhn, I don't know if I can reproduce this right now because I don't know if this is a real bug or not... I just noted that I can't rebuild Lime from source (I don't have a VS installed and I'm not admin of this PC).
I guess something got messed up and a old version of lime was used. I may try as soon as I get home.

**Comment by jgranick** [comment]
Okay, I reproduced the same TextField issue, it's fixed on the latest OpenFL

**Comment by NemoStein** [comment]
I've managed to rebuild Lime (Yay) and both bugs (z-ordering & textfield range) are fixed. =]
ps: I'm already working with the new "SWF base class" feature (https://github.com/openfl/openfl/commit/2abee666e229e866b0495c775a6324cfa3796542) and it work's like a charm! I'm really hoping for custom extensions (setting a base class in Animate) our a way to communicate from swf timeline to Haxe.
